name: Build & Push (fast)

on:
  push:
    branches: [ "main" ]      # триггер только от пуша в main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Buildx нужен для кэша; QEMU не нужен (мы собираем amd64 на amd64)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (cached)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          # максимально ускоряем за счёт кэша
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # для скорости обычно НЕ тянем свежие базовые слои
          pull: false
          # теги — только latest (и, по желанию, sha)
          tags: |
            ferlenzz/wan22-serverless-batch:latest
            ferlenzz/wan22-serverless-batch:${{ github.sha }}
          # опционально: фикс ревизии Wan2.2 (ускорит за счёт стабильного кэша)
          build-args: |
            WAN_REF=main
